swagger: '2.0'
info:
  version: 1.0.0
  title: Whole protein application
  description: >
    Swagger for Whole protein application
consumes:
  - application/json
produces:
  - application/json
basePath: '/api'
paths:
  /login:
    post:
      consumes:
        - application/json
      produces:
        - text/plain
      tags: [Login]
      description: Receives login credentials and returns token if credentials are valid
      parameters:
        - name: credentials
          in: body
          description: Credentials object with username and password
          required: true
          schema:
            $ref: '#/definitions/credentials'
      responses:
        '201':
          description: Valid token
          schema:
            type: string
            example: 'RS256.rafaadmin.hash'
        '401':
          description: Invalid username or password
        default:
          description: unexpected error
          schema:
            type: object
  /foods:
    get:
      tags: [Foods]
      description: Retrieves a list of available foods
      responses:
        '200':
          description: Array of foods
          schema:
            type: array
            example: [{ndbno: 10000, name: "Banana"}, {ndbno: 10010, name: "Apple"}, {ndbno: 10300, name: "Chocolate"}]
    post:
      produces: ["text/plain"]
      tags: [Foods]
      description: Adds an ingredient to collection of foods
      parameters:
        - name: ingredient
          in: body
          description: ingredient data to add
          required: true
          schema:
            $ref: '#/definitions/IngredientData'
      responses:
        '201':
          description: Sucessfully created, ID returned
          schema:
            type: string
            example: "==Rafadadawd"
  /foods/{ingredientID}:
    get:
      tags: [Foods]
      description: Get an ingredient by ingredient ID
      parameters:
        - name: ingredientID
          in: path
          required: true
          default: '==Rafadadawd'
          type: string
      responses:
        '200':
          description: Sucessful get
          schema:
            $ref: '#/definitions/IngredientData'      
    delete:
      tags: [Foods]
      description: Deletes an ingredient
      parameters:
        - name: ingredientID
          in: path
          required: true
          default: '==Rafadadawd'
          type: string
      responses:
        '204':
          description: Sucessfully deleted
    put:
      tags: [Foods]
      description: Updates an ingredient
      parameters:
        - name: ingredientID
          in: path
          required: true
          default: '==Rafadadawd'
          type: string
        - name: data
          in: body
          required: true
          description: new ingredient data
          schema:
            $ref: '#/definitions/IngredientData'
      responses:
        '200':
          description: Sucessfully updated
          schema:
            $ref: '#/definitions/IngredientData'
definitions:
  credentials:
    type: object
    required: ["username", "password"]
    properties:
      username:
        type: string
      password:
        type: string
    example: 
      username: evedraf
      password: admin
  token:
    type: object
    properties:
      header:
        type: object
      payload:
        type: object
      signature:
        type: object
  IngredientData:
    type: object
    required: ["name"]
    properties:
      name:
        type: string
    example: 
      name: "Lemon"
